### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Logmytech**
**Features added:**
**1) IP and UserAgent logging**
**2) Admin with `__str__` and `@python2_unicode_compatible` for easy navigation**
**3) Fixed sitemaps and changed priority to 0.5**
**4) Topic slug with dashes instead of underscores while maintaining backlink compatability (Doesn't break old underscore links)**
**5) Added metadata for SEO**
**6) IMPORTANT: Fixed failing builds. The build works and we won't have an ugly build-failing tag**
**7) Added redirect tests for Topic and no-slug Thread**
**8) Added tests for redirect of slug, old Topic(_)**
**9) Added test for Django 1.11**

@EatEmAll We need to fix the ugly failing build tag in the main repo. Please accept this pull request. The failing builds are caused due to Django 2.0 being installed instead of 1.10 in your repo.

https://stackoverflow.com/a/16203978/8893667

Advanced moderation is next. Going to take inspiration from askbot, biostars etc

**Added Admin and IP and User Agent Logging**
image

**Added MetaData**
image

Admin needs to be fixed. A lot needs to be added. What's a django site without admin, right?

IPAddress is working. On my localhost it shows 127.0.0.1 and for UserAgent that works perfectly and undoubtedly.

IP address is doubtful. Needs to be tested live and with proxies to see if anychanges are required.

### CODE REVIEW

**Comment by Logmytech** [comment]
image

**Comment by EatEmAll** [comment]
Thanks! I'm reviewing your changes right now.

**Comment by EatEmAll** [comment]
I made some changes & fixes for this pull request in this commit:
[https://github.com/EatEmAll/django-djeddit/commit/9f61cfd7f5618b3ed35ee6082e5e11d7a8b5090d](url)

- removed redundant methods: Topic.urlTitleOld and Topic.get_absolute_url
- removed _ check in Topic.getTopic since urlTitle is expected to contain -instead of _ for spaces
- views.topicPage: removed _ check in topic_title // this is handles in Topic.getTopic
- removed tests TopicPageTest.testRedirectsOld, ThreadPageTest.testRedirectsOld

- removed Thread.get_absolute_url
- added method Post.setMeta // updates ip & user_agent
- TopicModelTest.testGetTopic: testing wrong title // fixed
- CreateThreadTest._testSubmit, ReplyPostTest.testSubmit: test Post.setMeta method
views.py:
- createThread, replyPost: use Post.setMeta to avoid repeating code
- threadPage: removed http redirection

**Comment by Logmytech** [comment]
I created a new isuuse.

Old back links will break since you removed "_" compatability for topic URL.

**Pull request merged**
