### PR TITLE
Added slugify and slug redirects

### PR DESCRIPTION
**Pull request by Logmytech**
I have added slug redirects and get_slug and get_absolute_slug.

Please accept my pull request.

This is my first Github pull request and I have put a lot of work trying it and debugging it.

I'll be adding a lot more features.

Also maybe pinax integration in a different branch.

### CODE REVIEW

**Comment by Logmytech** [comment]
Have fixed awesome-slugify import error. Please verify it.(I'm not sure if it's you who is supposed to verify it, but I see verified for everything except fixed awesome-slugify fix)

**Comment by EatEmAll** [comment]
Sorry for the long delay. I'm reviewing your pull request right now & checking why tests are failing. I'll keep you updated. 
Please make a pull request next time to a different branch. You can see why it can be a problem to accept a pull requests with failing tests to master.

**Comment by Logmytech** [comment]
Which branch should I make a pull request to?

**Comment by Logmytech** [comment]
There seems to be an error that Python 3.3 isn't loaded in Travis CI and then the migration for slug isn't there.
So, you get a column doesn't exist in the test.

Then the slug URL redirects to 302 which fails some of the tests.

I'm new to this and guidance is appreciated.

**Comment by EatEmAll** [comment]
You can make a pull requests to dev branch. I'll keep you updated for any issues I'll encounter.

**Pull request closed without merging**
